builds:
  -
    skip: true
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
release:
  github:
    owner: okta
    name: okta-governance-sdk-golang
  draft: true
changelog:
  skip: true
