/*
Okta Governance API

Testing CollectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_CollectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CollectionsAPIService AddResourcesToCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.AddResourcesToCollection(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService AssignCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.AssignCollection(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService CreateCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CollectionsAPI.CreateCollection(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService DeleteCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		httpRes, err := apiClient.CollectionsAPI.DeleteCollection(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService DeleteCollectionResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string
		var resourceId string

		httpRes, err := apiClient.CollectionsAPI.DeleteCollectionResource(context.Background(), collectionId, resourceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService DeletePrincipalAssignment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string
		var assignmentId string

		httpRes, err := apiClient.CollectionsAPI.DeletePrincipalAssignment(context.Background(), collectionId, assignmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetCollection(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetCollectionResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string
		var resourceId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetCollectionResource(context.Background(), collectionId, resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetUnassignedUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetUnassignedUsers(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListCollectionAssignments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.ListCollectionAssignments(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListCollectionResources", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.ListCollectionResources(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListCollections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CollectionsAPI.ListCollections(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListCollectionsAssignments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CollectionsAPI.ListCollectionsAssignments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ReplaceCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.ReplaceCollection(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ReplaceCollectionResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string
		var resourceId string

		resp, httpRes, err := apiClient.CollectionsAPI.ReplaceCollectionResource(context.Background(), collectionId, resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService UpdatePrincipalAssignment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var collectionId string
		var assignmentId string

		httpRes, err := apiClient.CollectionsAPI.UpdatePrincipalAssignment(context.Background(), collectionId, assignmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
