/*
Okta Governance API

Testing EntitlementsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_EntitlementsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EntitlementsAPIService CreateEntitlement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitlementsAPI.CreateEntitlement(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService DeleteEntitlement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string

		httpRes, err := apiClient.EntitlementsAPI.DeleteEntitlement(context.Background(), entitlementId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService GetEntitlement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string

		resp, httpRes, err := apiClient.EntitlementsAPI.GetEntitlement(context.Background(), entitlementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService GetEntitlementValue", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string
		var valueId string

		resp, httpRes, err := apiClient.EntitlementsAPI.GetEntitlementValue(context.Background(), entitlementId, valueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService ListAllEntitlementValues", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitlementsAPI.ListAllEntitlementValues(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService ListEntitlementValues", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string

		resp, httpRes, err := apiClient.EntitlementsAPI.ListEntitlementValues(context.Background(), entitlementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService ListEntitlements", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitlementsAPI.ListEntitlements(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService ReplaceEntitlement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string

		resp, httpRes, err := apiClient.EntitlementsAPI.ReplaceEntitlement(context.Background(), entitlementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementsAPIService UpdateEntitlement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementId string

		resp, httpRes, err := apiClient.EntitlementsAPI.UpdateEntitlement(context.Background(), entitlementId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
