/*
Okta Governance API

Testing MyCatalogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_MyCatalogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MyCatalogsAPIService GetMyCatalogEntryRequestFieldsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string

		resp, httpRes, err := apiClient.MyCatalogsAPI.GetMyCatalogEntryRequestFieldsV2(context.Background(), entryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyCatalogsAPIService GetMyCatalogEntryUserRequestFieldsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string
		var userId string

		resp, httpRes, err := apiClient.MyCatalogsAPI.GetMyCatalogEntryUserRequestFieldsV2(context.Background(), entryId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyCatalogsAPIService GetMyEntryV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string

		resp, httpRes, err := apiClient.MyCatalogsAPI.GetMyEntryV2(context.Background(), entryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyCatalogsAPIService ListMyDefaultEntriesV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MyCatalogsAPI.ListMyDefaultEntriesV2(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyCatalogsAPIService ListMyEntryUsersV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string

		resp, httpRes, err := apiClient.MyCatalogsAPI.ListMyEntryUsersV2(context.Background(), entryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
