/*
Okta Governance API

Testing RequestTypesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_RequestTypesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RequestTypesAPIService CreateRequestType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RequestTypesAPI.CreateRequestType(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService DeleteRequestType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestTypeId string

		httpRes, err := apiClient.RequestTypesAPI.DeleteRequestType(context.Background(), requestTypeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService GetRequestType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestTypeId string

		resp, httpRes, err := apiClient.RequestTypesAPI.GetRequestType(context.Background(), requestTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService ListAllRequestTeams", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RequestTypesAPI.ListAllRequestTeams(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService ListAllRequestTypes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RequestTypesAPI.ListAllRequestTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService PublishRequestType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestTypeId string

		resp, httpRes, err := apiClient.RequestTypesAPI.PublishRequestType(context.Background(), requestTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestTypesAPIService UnpublishRequestType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestTypeId string

		resp, httpRes, err := apiClient.RequestTypesAPI.UnpublishRequestType(context.Background(), requestTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
