/*
Okta Governance API

Testing RequestSettingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_RequestSettingsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RequestSettingsAPIService GetOrgRequestSettingsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RequestSettingsAPI.GetOrgRequestSettingsV2(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestSettingsAPIService GetRequestSettingsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string

		resp, httpRes, err := apiClient.RequestSettingsAPI.GetRequestSettingsV2(context.Background(), resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestSettingsAPIService UpdateOrgRequestSettingsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RequestSettingsAPI.UpdateOrgRequestSettingsV2(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestSettingsAPIService UpdateResourceRequestSettingsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string

		resp, httpRes, err := apiClient.RequestSettingsAPI.UpdateResourceRequestSettingsV2(context.Background(), resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
