/*
Okta Governance API

Testing RequestConditionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_RequestConditionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RequestConditionsAPIService ActivateResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var requestConditionId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.ActivateResourceRequestConditionV2(context.Background(), resourceId, requestConditionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService CreateResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.CreateResourceRequestConditionV2(context.Background(), resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService DeactivateResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var requestConditionId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.DeactivateResourceRequestConditionV2(context.Background(), resourceId, requestConditionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService DeleteResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var requestConditionId string

		httpRes, err := apiClient.RequestConditionsAPI.DeleteResourceRequestConditionV2(context.Background(), resourceId, requestConditionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService GetResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var requestConditionId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.GetResourceRequestConditionV2(context.Background(), resourceId, requestConditionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService ListResourceRequestConditionsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.ListResourceRequestConditionsV2(context.Background(), resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestConditionsAPIService UpdateResourceRequestConditionV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var requestConditionId string

		resp, httpRes, err := apiClient.RequestConditionsAPI.UpdateResourceRequestConditionV2(context.Background(), resourceId, requestConditionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
