/*
Okta Governance API

Testing RequestSequencesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_RequestSequencesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RequestSequencesAPIService DeleteRequestSequenceV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		httpRes, err := apiClient.RequestSequencesAPI.DeleteRequestSequenceV2(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestSequencesAPIService GetResourceRequestSequenceV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string
		var sequenceId string

		resp, httpRes, err := apiClient.RequestSequencesAPI.GetResourceRequestSequenceV2(context.Background(), resourceId, sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RequestSequencesAPIService ListResourceRequestSequencesV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceId string

		resp, httpRes, err := apiClient.RequestSequencesAPI.ListResourceRequestSequencesV2(context.Background(), resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
