/*
Okta Governance API

Testing ReviewsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_ReviewsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReviewsAPIService GetReview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var reviewId string

		resp, httpRes, err := apiClient.ReviewsAPI.GetReview(context.Background(), reviewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService ListReviews", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ReviewsAPI.ListReviews(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService ReassignReviews", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var campaignId string

		resp, httpRes, err := apiClient.ReviewsAPI.ReassignReviews(context.Background(), campaignId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
