/*
Okta Governance API

Testing GrantsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_GrantsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GrantsAPIService CreateGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GrantsAPI.CreateGrant(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GrantsAPIService GetGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.GrantsAPI.GetGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GrantsAPIService ListGrants", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GrantsAPI.ListGrants(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GrantsAPIService ReplaceGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.GrantsAPI.ReplaceGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GrantsAPIService UpdateGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.GrantsAPI.UpdateGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
