/*
Okta Governance API

Testing MyRequestsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_MyRequestsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MyRequestsAPIService CreateMyRequestV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string

		resp, httpRes, err := apiClient.MyRequestsAPI.CreateMyRequestV2(context.Background(), entryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyRequestsAPIService GetMyRequestV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string
		var requestId string

		resp, httpRes, err := apiClient.MyRequestsAPI.GetMyRequestV2(context.Background(), entryId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
