/*
Okta Governance API

Testing CatalogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_CatalogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CatalogsAPIService GetCatalogEntryRequestFieldsV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string
		var userId string

		resp, httpRes, err := apiClient.CatalogsAPI.GetCatalogEntryRequestFieldsV2(context.Background(), entryId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogsAPIService GetCatalogEntryV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entryId string

		resp, httpRes, err := apiClient.CatalogsAPI.GetCatalogEntryV2(context.Background(), entryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogsAPIService ListAllDefaultEntriesV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CatalogsAPI.ListAllDefaultEntriesV2(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CatalogsAPIService ListAllDefaultUserEntriesV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.CatalogsAPI.ListAllDefaultUserEntriesV2(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
