/*
Okta Governance API

Testing EntitlementBundlesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package governance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/okta/okta-governance-sdk-golang/governance"
)

func Test_governance_EntitlementBundlesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EntitlementBundlesAPIService CreateEntitlementBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitlementBundlesAPI.CreateEntitlementBundle(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementBundlesAPIService DeleteEntitlementBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementBundleId string

		httpRes, err := apiClient.EntitlementBundlesAPI.DeleteEntitlementBundle(context.Background(), entitlementBundleId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementBundlesAPIService GetentitlementBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementBundleId string

		resp, httpRes, err := apiClient.EntitlementBundlesAPI.GetentitlementBundle(context.Background(), entitlementBundleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementBundlesAPIService ListEntitlementBundles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitlementBundlesAPI.ListEntitlementBundles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitlementBundlesAPIService ReplaceEntitlementBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entitlementBundleId string

		resp, httpRes, err := apiClient.EntitlementBundlesAPI.ReplaceEntitlementBundle(context.Background(), entitlementBundleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
